"""Add website field to Tool model

Revision ID: 5faa19f32fc7
Revises: 5aa6a93bdf80
Create Date: 2024-09-14 13:08:52.171796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5faa19f32fc7'
down_revision = '5aa6a93bdf80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool', schema=None) as batch_op:
        batch_op.drop_column('website')

    # ### end Alembic commands ###
